version: 2

sources:
  - name: paris_orly
    database: 
    schema: paris_orly
    tables:
      - name: raw_flights
        columns:
          - name: flight_number
            tests: [not_null]
          - name: snapshot_time
            tests: [not_null]
      - name: flight_events
        columns:
          - name: event_id
            tests: [not_null]

models:
  - name: stg_raw_flights
    columns:
      - name: flight_number
        tests: [not_null]
      - name: flight_type
        tests:
          - accepted_values:
              values: ["departure", "arrival"]
  - name: mart_live_board
    columns:
      - name: flight_number
        tests: [not_null, unique]
